<a href="https://colab.research.google.com/github/mushroom3969/PyTorch_Class/blob/main/fundemental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

print(torch.__version__)

2.1.0+cu121


In [ ]:
!nvidia-smi

Mon Feb 26 12:36:00 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##Tensor

In [ ]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Ge tensor back as python int
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape #0dim有多少, 1dim有多少, 2dim有多少

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###  Random Tensor

Random Tensor are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> updatae ramdom numbers`

In [ ]:
#random tensor of shape (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2509, 0.1421, 0.7905, 0.9578],
        [0.9821, 0.6062, 0.2801, 0.9198],
        [0.0658, 0.2183, 0.5020, 0.5002]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, weight, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [ ]:
# all Zero

zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Range of tensors and tensors-like

In [ ]:
# torch.arange()

one_to_ten = torch.arange(start=0, end=1.1e1, step=1)
one_to_ten

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# tensors alike

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Tensor datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with pytorch & deep learning:
1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on the right device.


In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tnesor
                               device = None, # What device is your tensor on. default is cpu(None), other like gpu(cuda)
                               requires_grad=False)  #Whether or not to track tensor gradient with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 5, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 30., 81.], dtype=torch.float16)


### Getting information form tensor (tensor attribute)

1. Tensors not right datatype - to do get datatype form a tensor, can use `tensor.dtype
2. Tensors not right shape - to get shape form a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device form a tensor, can use `tensor.device`

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5471, 0.3255, 0.1204, 0.3412],
        [0.0440, 0.5204, 0.0978, 0.1017],
        [0.1681, 0.6173, 0.8936, 0.8890]])

In [ ]:
# find out details anout some tensor
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.5471, 0.3255, 0.1204, 0.3412],
        [0.0440, 0.5204, 0.0978, 0.1017],
        [0.1681, 0.6173, 0.8936, 0.8890]])
torch.float32
torch.Size([3, 4])
cpu


### Manipulating Tensor (Tensor operations)

Tensor operation:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# create tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
1 * 1 + 2 * 2 + 3 * 3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.66 ms, sys: 858 µs, total: 2.52 ms
Wall time: 2.13 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 472 µs, sys: 0 ns, total: 472 µs
Wall time: 373 µs


tensor(14)

In [ ]:
tensor_a = torch.tensor([[1, 10],
                         [2, 5],
                         [3, 7]])

tensor_b = torch.tensor([[1, 10],
                         [3, 5],
                         [3, 6]])

torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_a.T

tensor([[ 1,  2,  3],
        [10,  5,  7]])

In [ ]:
torch.matmul(tensor_a.T, tensor_b)

tensor([[ 16,  38],
        [ 46, 167]])

## Tensor aggregation

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min

(tensor(0), <function Tensor.min>)

In [ ]:
torch.max(x), x.max

(tensor(90), <function Tensor.max>)

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
x.dtype

torch.int64

In [ ]:
x = x.type(torch.float32)
x.mean()

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450.)

## Finding the position min and max

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[x.argmin()]

tensor(0.)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[x.argmax()]

tensor(90.)

## Reshaping, stacking, Squeezing, Unsqueezing

* Reshapinf - reshape an input tensor to a define tensor
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
*Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimension from tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimension permuted(swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(3, 3)
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
z = x.view(3, 3)
z, z.shape # z has same memory as original tensor

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
z_stack = torch.stack([z, z, z, z], dim=0)
z_stack, z_stack.shape

(tensor([[[5., 2., 3.],
          [5., 5., 6.],
          [5., 8., 9.]],
 
         [[5., 2., 3.],
          [5., 5., 6.],
          [5., 8., 9.]],
 
         [[5., 2., 3.],
          [5., 5., 6.],
          [5., 8., 9.]],
 
         [[5., 2., 3.],
          [5., 5., 6.],
          [5., 8., 9.]]]),
 torch.Size([4, 3, 3]))

In [ ]:
z_stack = torch.stack([z, z, z, z], dim=1)
z_stack, z_stack.shape

(tensor([[[5., 2., 3.],
          [5., 2., 3.],
          [5., 2., 3.],
          [5., 2., 3.]],
 
         [[5., 5., 6.],
          [5., 5., 6.],
          [5., 5., 6.],
          [5., 5., 6.]],
 
         [[5., 8., 9.],
          [5., 8., 9.],
          [5., 8., 9.],
          [5., 8., 9.]]]),
 torch.Size([3, 4, 3]))

In [ ]:
z, z.squeeze(dim=0), z.squeeze(dim=1),

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]))

In [ ]:
z.reshape(1,9)

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
z.reshape(1,9).squeeze(dim=0), z.reshape(1,9).squeeze(dim=1)

(tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]),
 tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]))

In [ ]:
z.reshape(3,1,3)

tensor([[[5., 2., 3.]],

        [[5., 5., 6.]],

        [[5., 8., 9.]]])

In [ ]:
z.reshape(3,1,3).squeeze()

tensor([[5., 2., 3.],
        [5., 5., 6.],
        [5., 8., 9.]])

In [ ]:
z.unsqueeze(dim=1)

tensor([[[5., 2., 3.]],

        [[5., 5., 6.]],

        [[5., 8., 9.]]])

In [ ]:
x_ori = torch.rand(size=(224, 224, 3))
x_ori.shape

torch.Size([224, 224, 3])

In [ ]:
x_permute = torch.permute(x_ori, dims=(2,0,1)) # change axis 0->2 1->0 2->1
x_permute.shape

torch.Size([3, 224, 224])

In [ ]:
x_permute[0, 0, 0], x_ori[0, 0, 0]

(tensor(0.6576), tensor(0.6576))

## Indexing

Similar with numpy

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[:,0,:]

tensor([[1, 2, 3]])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

## Pytorch tensor & Numpy

* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> numpy -> `torch.Tensor.numpy()`

In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # pytorh will reflect default dtype in numpy
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

neural network learns:
`start with random numbers -> tensor operations -> update random number to try and make them better representations of the data -> again -> again...`

To reduce the randomness in neural networks and Pytorch comes the concept of a random seed.

In [ ]:
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.8867, 0.2411, 0.8977, 0.9958],
        [0.7141, 0.4450, 0.6106, 0.0849],
        [0.8985, 0.2048, 0.2106, 0.2368]])
tensor([[0.8386, 0.0178, 0.6365, 0.5899],
        [0.4111, 0.2627, 0.3557, 0.5237],
        [0.7927, 0.0891, 0.5635, 0.0950]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## 1. Rinning tensors and Pytorch object on the GPUs

1. Google Colab
2. Own GPU
3. Cloud computing - GCP, AWS, Azure

2 and 3 need setting up when using Pytorch

In [ ]:
!nvidia-smi

Tue Feb 27 03:48:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 2. Check for the GPU acess with Pytorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and nodels) on the GPU

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensor back to the CPU

In [ ]:
# If tensor is on GPU, it can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])